/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f0xx.h"

void one(int c){
	int j;
	for(;c>0;c--){
		GPIOA->BSRR = (1<<5); // set
		for(j=0;j<200000;j++);
	}
}

void zero(int c){
	int j;
	for(;c>0;c--){
			GPIOA->BRR = (1<<5); // reset
			for(j=0;j<200000;j++);
		}
}


int main(void)
{


	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;

	while(1){
		one(1);
		zero(1);
		one(1);
		zero(1);
		one(1);

		zero(2);

		one(3);
		zero(1);
		one(3);
		zero(1);
		one(3);

		zero(2);

		one(1);
		zero(1);
		one(1);
		zero(1);
		one(1);

		zero(8);

	}

}


